package cz.matejkripner.ai;

import cz.matejkripner.core.Movement;
import sun.java2d.opengl.OGLContext;

import static cz.matejkripner.core.Movement.*;

/**
 * Created by Kripner on 4/17/2015.
 */
public enum MAP {
    FIRST(GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD,, TURN_LEFT, GO_AHEAD
    ,GO_BACK, TURN_LEFT, TURN_LEFT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_BACK, TURN_LEFT,
            GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_BACK, GO_BACK
            ,GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD,
            TURN_RIGHT, GO_BACK, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_BACK, GO_AHEAD, GO_AHEAD, GO_AHEAD
            , GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD,
            GO_BACK, TURN_LEFT, GO_BACK, GO_AHEAD, GO_AHEAD, GO_AHEAD
    ),
    SECOND(GO_AHEAD, TURN_LEFT, GO_BACK, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD
    ,GO_AHEAD, TURN_LEFT, GO_BACK, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_BACK, GO_AHEAD, TURN_RIGHT, GO_AHEAD
    , GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_BACK, GO_BACK, TURN_LEFT, GO_AHEAD, TURN_RIGHT, GO_AHEAD, TURN_LEFT,
            GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, TURN_RIGHT, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_LEFT, GO_AHEAD,
            GO_AHEAD, TURN_RIGHT, GO_BACK, GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_BACK, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD,
            TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_BACK, GO_AHEAD, TURN_RIGHT, GO_AHEAD)
    ,THIRD(GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_BACK
    ,GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT    , GO_AHEAD, GO_AHEAD
    , TURN_RIGHT, GO_AHEAD, GO_BACK, GO_BACK, TURN_LEFT, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, TURN_LEFT, GO_BACK,
            GO_BACK, GO_BACK, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_BACK, GO_AHEAD,
            GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD,
            GO_BACK, TURN_LEFT,GO_AHEAD
    ),
    FOURTH(GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_BACK, GO_AHEAD, GO_AHEAD
    , GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD, GO_BACK, TURN_LEFT, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT,
            GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, TURN_LEFT, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD,GO_AHEAD, TURN_LEFT, GO_AHEAD,
            GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD, TURN_LEFT, GO_AHEAD, TURN_RIGHT, GO_AHEAD, TURN_RIGHT, GO_AHEAD, TURN_RIGHT,
            GO_AHEAD, TURN_LEFT, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_BACK, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_AHEAD, TURN_RIGHT, GO_AHEAD
    ,GO_AHEAD, GO_AHEAD, GO_BACK, TURN_RIGHT, GO_AHEAD, GO_AHEAD, GO_AHEAD, GO_BACK, TURN_LEFT, GO_BACK, GO_AHEAD, GO_AHEAD);


    private Movement[] movements;

    MAP(Movement ... movements) {

    }
}
